# https://taskfile.dev

version: '3'

vars:
  SRC_FILE: main.c

tasks:
  build:
    cmds:
      - clang -Wall -Wextra -o main {{.SRC_FILE}}
    silent: true
  run:
    cmds:
      - ./main
    silent: true
  build and run:
    cmds:
      - task build
      - task run
    silent: true
